baseURL = 'https://abowchen2025.github.io/tech-pulse/'
locale = 'zh-tw'
title = 'Tech Pulse 產業脈動快報'
theme = 'PaperMod'

[taxonomies]
  tag = 'tags'
  glossary = 'glossary_term'

[params]
  ShowReadingTime = true
  ShowWordCount = true
  ShowToc = true
  ShowShareButtons = true